{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "iom.serviceAccountName" . }}
  labels:
    {{- include "iom.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name:  {{ include "iom.serviceAccountName" . }}-pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name:  {{ include "iom.serviceAccountName" . }}-api-access
roleRef:
  apiGroup: ""
  kind: Role
  name:  {{ include "iom.serviceAccountName" . }}-pod-reader
subjects:
- kind: ServiceAccount
  name:  {{ include "iom.serviceAccountName" . }}
{{- end }}
