{{- if not .Values.serverName -}}
{{- $values_ := set .Values "serverName" "appserver" -}}
{{- end -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "icm-as.fullname" . }}
  {{- if .Values.deploymentAnnotations }}
  annotations: {{- toYaml .Values.deploymentAnnotations | trim | nindent 4 }}
  {{- end }}
  labels:
    app: {{ include "icm-as.fullname" . }}
    {{ include "icm-as.chartLabel" . | indent 4 | trim }}
    {{ include "icm-as.datadogLabels" . | indent 4 | trim }}
    {{- if .Values.deploymentLabels }}
      {{- toYaml .Values.deploymentLabels | trim | nindent 4 }}
    {{- end }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: icm-as
      release: {{ include "icm-as.fullname" . }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{ include "icm-as.podData" . | indent 6 | trim }}
      labels:
        app: icm-as
        release: {{ include "icm-as.fullname" . }}
        {{ include "icm-as.datadogLabels" . | indent 8 | trim }}
        {{ include "icm-as.podLabels" . | indent 8 | trim }}
    spec:
      {{ include "icm-as.nodeSelector" . | indent 6 | trim }}
      {{ include "icm-as.imagePullSecrets" . | indent 6 | trim }}
      containers:
      - name: icm-as-server
        {{ include "icm-as.image" . | indent 8 | trim }}
        {{ include "icm-as.env" . | indent 8 | trim }}
        {{ include "icm-as.ports" . | indent 8 | trim }}
        {{ include "icm-as.resources" . | indent 8 | trim }}
        {{ include "icm-as.volumeMounts" . | indent 8 | trim }}
        {{ include "icm-as.probes" . | indent 8 | trim }}
        {{ include "icm-as.lifecycle" . | indent 8 | trim }}
      {{ include "icm-as.initContainers" . | indent 6 | trim }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      {{ include "icm-as.podSecurityContext" . | indent 6 | trim }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds | default 30 }}
      {{ include "icm-as.volumes" . | indent 6 | trim }}
